version: "3.7"
services:
  db: 
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "3005"
      MYSQL_USER: "root"
      MYSQL_DATABASE: "metigy"
    volumes:
      - ./mysqldata:/var/test/lib/mysql/data
    ports:
      - "3306:3306"
    container_name: mydb
  web:
    build: .
    depends_on: 
      - db
    ports:
      - "3005:3005" 
      - "3000:3000"
    
  
    
